/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LinksRouteImport } from './routes/links'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteProjetosRouteImport } from './routes/_site/projetos'
import { Route as SiteGamedevRouteImport } from './routes/_site/gamedev'
import { Route as SiteCertificadosRouteImport } from './routes/_site/certificados'

const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjetosRoute = SiteProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGamedevRoute = SiteGamedevRouteImport.update({
  id: '/gamedev',
  path: '/gamedev',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCertificadosRoute = SiteCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/links': typeof LinksRoute
  '/certificados': typeof SiteCertificadosRoute
  '/gamedev': typeof SiteGamedevRoute
  '/projetos': typeof SiteProjetosRoute
}
export interface FileRoutesByTo {
  '/links': typeof LinksRoute
  '/certificados': typeof SiteCertificadosRoute
  '/gamedev': typeof SiteGamedevRoute
  '/projetos': typeof SiteProjetosRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/links': typeof LinksRoute
  '/_site/certificados': typeof SiteCertificadosRoute
  '/_site/gamedev': typeof SiteGamedevRoute
  '/_site/projetos': typeof SiteProjetosRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/links' | '/certificados' | '/gamedev' | '/projetos'
  fileRoutesByTo: FileRoutesByTo
  to: '/links' | '/certificados' | '/gamedev' | '/projetos' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/links'
    | '/_site/certificados'
    | '/_site/gamedev'
    | '/_site/projetos'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  LinksRoute: typeof LinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projetos': {
      id: '/_site/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof SiteProjetosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gamedev': {
      id: '/_site/gamedev'
      path: '/gamedev'
      fullPath: '/gamedev'
      preLoaderRoute: typeof SiteGamedevRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/certificados': {
      id: '/_site/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof SiteCertificadosRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteCertificadosRoute: typeof SiteCertificadosRoute
  SiteGamedevRoute: typeof SiteGamedevRoute
  SiteProjetosRoute: typeof SiteProjetosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCertificadosRoute: SiteCertificadosRoute,
  SiteGamedevRoute: SiteGamedevRoute,
  SiteProjetosRoute: SiteProjetosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  LinksRoute: LinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
