/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as LinksRouteImport } from './routes/links'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as IndexRouteImport } from './routes/index'

const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/links': typeof LinksRoute
  '/projetos': typeof ProjetosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/links': typeof LinksRoute
  '/projetos': typeof ProjetosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/links': typeof LinksRoute
  '/projetos': typeof ProjetosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificados' | '/links' | '/projetos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificados' | '/links' | '/projetos'
  id: '__root__' | '/' | '/certificados' | '/links' | '/projetos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadosRoute: typeof CertificadosRoute
  LinksRoute: typeof LinksRoute
  ProjetosRoute: typeof ProjetosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadosRoute: CertificadosRoute,
  LinksRoute: LinksRoute,
  ProjetosRoute: ProjetosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
